### ISSUE TITLE
global scripts 

### ISSUE THREAD

**Issue by boigamer12345** [sayofthelor/lore-engine#15]
### What feature do you want to get added on the **base** engine?

basically what the title says
scripts that can load outside songs like lunar engine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by sayofthelor** [comment]
i'm actually a contributor for lunar engine, and while i can say that is cool, our engines have fundamentally different goals

also this version of lore engine probably won't get very many new feature updates, since i'm working on a rewrite
