### ISSUE TITLE
Second Vocal File can be selected in the chart editor.

### ISSUE THREAD

**Issue by Sonicgamer2000** [sayofthelor/lore-engine#16]
### What is your question?

I’m in the chart editor and when I got in the chart editor I see “HasVoiceTrack2.” Someone explain to me why this engine specifically has two vocal files used in one song?

**Comment by sayofthelor** [comment]
it's for multiple vocal tracks so you can mute bf's vocals while the opponent still sings
`Voices` is opponent and `Voices2` is bf
